### ISSUE TITLE
Add workflow to README

### ISSUE THREAD

**Issue by jasonmp85** [petere/homebrew-postgresql#11]
@petere — Are you using this package to build and test PostgreSQL extensions against multiple PostgreSQL installations? If so, can you add an example workflow to the `README`? I ran into two problems when trying to use this package and wondered whether I was doing anything wrong:

  * `pg_createcluster` and friends have [special logic][] to determine the socket directory. Without passing any special arguments to them, this ends up being `/usr/local/var/run/postgresql`.

  So long as I use the `pg_wrapper`-linked versions of commands (such as `psql`) this is OK, but using a given version's `psql` directly uses the PostgreSQL default of `/tmp`.

  I feel that `psql` with just a port number should be able to connect to a cluster created with `pg_createcluster` with no arguments (i.e. the simplest case should "just work"). This comes up in practice when running a PGXS-based build as `pg_regress` invokes a version's `psql` directly (i.e. not through the wrappers)

  * This is not really your doing, but I was _very_ surprised to find that `pg_config` isn't just a link to `pg_wrapper` but instead is a script that executes the `pg_config` with the highest available version (it doesn't even respect the `PGCLUSTER` variable, if set).

  If I have 9.3 and 9.4 installed, a simple PGXS-based extension can only be built and installed against 9.4: when PGXS invokes `pg_config` it will always receive the 9.4 version. This is the deal breaker: I don't see how I can use these tools to build extensions against multiple PostgreSQL versions, though that is ostensibly precisely what they're here for.

For the moment my workaround is this:

  * I've replaced `postgresql-common`'s `pg_config` and replaced it with a symlink to `pg_wrapper`

  * I "wrote" a `chruby`-"inspired" [script][chpg] which keeps track of the "current" PostgreSQL cluster by setting `PGHOST`, `PGPORT`, and `PGCLUSTER`. My profile sets it to `9.4/main` when I log in, so these variables are always at least set.

With the above changes it's pretty easy to test PGXS-based extensions, but I felt like this should have been easier to devise. Do you have a workflow you could share?

[special logic]: https://github.com/petere/postgresql-common/blob/5f9fe4ec10cf9ec625eacc65881aab961ef2aba1/pg_createcluster#L387-L413
[chpg]: https://gist.github.com/jasonmp85/218f3bba809ec086343a

**Comment by petere** [comment]
The Debian logic to sometimes use `/usr/local/var/run/postgresql/` for the socket was obviously confusing and not necessary for Homebrew, so I removed that.

The reason `pg_config` is set up this way is that you can build *clients* out of the box, because they always get the latest libpq.  I can see the appeal of your idea, but `pg_wrapper` is ostensibly a client-side tool, so this would create some conceptual mixups.  I think it's OK if you put your own symlink in place if that's the behavior your prefer.

Extensions normally respect a `PG_CONFIG` environment variable or path settings, so I would normally use one of those.  `postgresql-common` also has a tool `pg_buildext` for this purpose, but I don't think it is of much use outside of Debian.  Admittedly, extension building isn't my primary use of these packages, so I haven't given it much thought.

I think this is worth further exploration, but maybe as a separate bug report, and in coordination with upstream.
