### ISSUE TITLE
Can't brew install with gnu-sed installed --with-default-names

### ISSUE THREAD

**Issue by caseyallenshobe** [petere/homebrew-postgresql#29]
Error produced saying that gsed doesn't exist...  Probably best to check `sed --version` first to see if it's usable.

**Comment by petere** [comment]
Why package, what is your command, what is the output?

**Comment by alexeyklyukin** [comment]
I have the same issue when installing `postgresql-commons`, as it refused to install with the following error:

> gsed -i \
>         -e "s,^use PgCommon,use lib '/usr/local/Cellar/postgresql-common/HEAD-74c810d/share/postgresql-common'; &,g" \
>         -e 's,/etc/postgresql,/usr/local/etc/postgresql,' \
>         -e 's,/var/lib/postgresql,/usr/local/var/lib/postgresql,' \
>         -e 's,/var/log/postgresql,/usr/local/var/log/postgresql,' \
>         -e 's,/var/run/postgresql,/usr/local/var/run/postgresql,' \
>         -e 's,/bin:/usr/bin,/usr/local/Cellar/postgresql-common/HEAD-74c810d/bin:/bin:/usr/bin,' \
>         -e '/version/s,/usr/lib/postgresql/,/usr/local/opt/postgresql@,g' \
>         /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_wrapper /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_config /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_conftool /usr/local/Cellar/postgresql-common/HE
> AD-74c810d/bin/pg_createcluster /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_ctlcluster /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_dropcluster /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_lsclusters /usr
> /local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_updatedicts /usr/local/Cellar/postgresql-common/HEAD-74c810d/bin/pg_upgradecluster \
>         /usr/local/etc/postgresql-common/createcluster.conf \
>         /usr/local/Cellar/postgresql-common/HEAD-74c810d/share/man/man1/*.1 /usr/local/Cellar/postgresql-common/HEAD-74c810d/share/man/man5/*.5 /usr/local/Cellar/postgresql-common/HEAD-74c810d/share/man/man8/*.8 \
>         /usr/local/Cellar/postgresql-common/HEAD-74c810d/share/postgresql-common/PgCommon.pm
> /bin/sh: gsed: command not found
> 

I think the problem was me instaling `gnu-sed` with `--with-default-names`, opting to have the command named `sed` and not `gsed`.  I tried symlinking `/usr/local/bin/gsed` -> `/usr/local/Cellar/gnu-sed/4.4/bin/sed` (location of the `sed` binary on my system), but it didn't work. Eventually, I just copied `/usr/local/Cellar/gnu-sed/4.4/bin/sed` to `/usr/local/Cellar/gnu-sed/4.4/bin/gsed` and it worked! I suspect the issue is that Homebrew searches for the dependencies (in our case `gnu-sed`) in the  installation path of the package and ignores symlinks.

**Comment by caseyallenshobe** [comment]
Right - the point is thet when the gnu-sed package is installed with default names used for the binaries, there is no command named gsed on the system. The problem is the script in postgresql-common is hardcoded to require an executable named gsed rather than sed.
